[build]
  command = "npm run build"
  publish = "dist"

# React Router handling
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Clerk callback handling
[[redirects]]
  from = "/sso-callback"
  to = "/index.html"
  status = 200
